# fly.toml app configuration file generated for sc-links on 2023-08-19T19:09:07+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sc-links"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 3030
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
